GET http://localhost:3001/notes HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOjUsImlhdCI6MTYwMzEwMjY3OH0.auYClabtK6VtiajnGV_7oW5wzOlLW5GqcvdlT7Fs27A